version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql
  api:
    env_file: ./.env.prod
    build: .
    container_name: wefit
    links:
      - "mysqldb:mysqldb"
    ports:
      - 4568:4568
    
