apiVersion: apps/v1
kind: Deployment
metadata:
  name: wefit-dp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: wefit
  template:
    metadata:
      labels:
        app: wefit
    spec:
      containers:
      - name: wefit-api
        image: devtfo/wefit
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4568
        env:
          - name: DATABASE_URL
            value: "mysql://root:senha_root_123@wefit-db-service:3306/wefit"

---
apiVersion: v1
kind: Pod
metadata:
  name: wefit-db
  labels:
    app: wefit-db
spec:
  containers:
  - name: mysqldb
    image: mysql:5.6
    ports:
      - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: senha_root_123
      - name: MYSQL_DATABASE
        value: wefit
---
apiVersion: v1
kind: Service
metadata:
  name: wefit-service
spec:
  type: LoadBalancer
  selector:
    app: wefit
  ports:
  - port: 4568
    targetPort: 4568
---
apiVersion: v1
kind: Service
metadata:
  name: wefit-db-service
spec:
  type: NodePort
  selector:
    app: wefit-db
  ports:
  - port: 3306
    targetPort: 3306